<script setup>
import {ref} from "vue";
import {date} from "quasar";
import { FreeMode, Pagination } from 'swiper/modules';
import { Swiper, SwiperSlide } from 'swiper/vue';
const modules = ref([FreeMode]);
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';

const props = defineProps({
  players: {
    type: Array,
    required: true
  },
  selectedPlayer: {
    type: Object,
    required: false
  }
})

const emits = defineEmits(['selectPlayer'])


</script>

<template>
  <swiper
    :slidesPerView="8"
    :spaceBetween="30"
    :freeMode="true"
    :pagination="{
      clickable: true,
    }"
    :modules="modules"
    class="mySwiper"
  >
    <swiper-slide
       :class="selectedPlayer?.uyeNo === player.uyeNo ? 'currentPlayer heartbeat' : ''"
       v-ripple
       class="cursor-pointer"
       v-for="(player,index) in players"
       :key="index"
       @click="emits('selectPlayer', player)"

    >
      <q-img
        :src="'data:image/jpeg;base64,'+player.resim"
        class="full-width"
        fit="fill"

        >
        <div class="absolute-bottom  " style="padding: 0!important;">
          <div class="text-subtitle1 text-bold text-center">
            #{{player?.uyeNo}}
          </div>
          <div class="text-subtitle2 text-bold text-center">
            {{player?.adSoyad}}
          </div>
        </div>
      </q-img>
      <div class="text-subtitle2 row">
        <span class="col-12 text-center">
          Avg: {{player?.avgBet}}
        </span>
        <span class="col-12 text-center">
<!--       {{$t('base.time')}}  -->
          {{   date.formatDate(player?.timeIn, 'DD.MM.YYYY HH:mm')}}
        </span>
      </div>
    </swiper-slide>

  </swiper>
</template>

<style scoped>
 .currentPlayer {
   border: 1px solid red; border-radius: 5px; padding: 3px
 }


 /* ----------------------------------------------
 * Generated by Animista on 2023-6-8 13:7:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
 .heartbeat {
   -webkit-animation: heartbeat 2.5s ease-in-out infinite alternate-reverse both;
   animation: heartbeat 2.5s ease-in-out infinite alternate-reverse both
 }

 @-webkit-keyframes heartbeat {
   from {
     -webkit-transform: scale(1);
     transform: scale(1);
     -webkit-transform-origin: center center;
     transform-origin: center center;
     -webkit-animation-timing-function: ease-out;
     animation-timing-function: ease-out
   }
   10% {
     -webkit-transform: scale(.91);
     transform: scale(.91);
     -webkit-animation-timing-function: ease-in;
     animation-timing-function: ease-in
   }
   17% {
     -webkit-transform: scale(.98);
     transform: scale(.98);
     -webkit-animation-timing-function: ease-out;
     animation-timing-function: ease-out
   }
   33% {
     -webkit-transform: scale(.87);
     transform: scale(.87);
     -webkit-animation-timing-function: ease-in;
     animation-timing-function: ease-in
   }
   45% {
     -webkit-transform: scale(1);
     transform: scale(1);
     -webkit-animation-timing-function: ease-out;
     animation-timing-function: ease-out
   }
 }

 @keyframes heartbeat {
   from {
     -webkit-transform: scale(1);
     transform: scale(1);
     -webkit-transform-origin: center center;
     transform-origin: center center;
     -webkit-animation-timing-function: ease-out;
     animation-timing-function: ease-out
   }
   10% {
     -webkit-transform: scale(.91);
     transform: scale(.91);
     -webkit-animation-timing-function: ease-in;
     animation-timing-function: ease-in
   }
   17% {
     -webkit-transform: scale(.98);
     transform: scale(.98);
     -webkit-animation-timing-function: ease-out;
     animation-timing-function: ease-out
   }
   33% {
     -webkit-transform: scale(.87);
     transform: scale(.87);
     -webkit-animation-timing-function: ease-in;
     animation-timing-function: ease-in
   }
   45% {
     -webkit-transform: scale(1);
     transform: scale(1);
     -webkit-animation-timing-function: ease-out;
     animation-timing-function: ease-out
   }
 }
</style>
